CREATE SCHEMA `ylazy` DEFAULT CHARACTER SET utf8 ;

ALTER TABLE `ylazy`.`lazy_task` 
CHANGE COLUMN `result_json` `result_json` LONGTEXT NULL DEFAULT NULL ,
CHANGE COLUMN `url` `url` LONGTEXT NULL DEFAULT NULL ;

